### ISSUE TITLE
Error when running in terminal

### ISSUE THREAD

**Issue by WriteThatDown** [brettz9/convert-manifest-format#2]
I ran the command `npx convert-manifest-format --firefox` and it gave the following error output:
```
file:///home/backsideofdawn/node_modules/convert-manifest-format/bin/index.js:7
const file = await readFile(manifestPath);
             ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_j```

**Comment by brettz9** [comment]
What version of Node are you running?

**Comment by WriteThatDown** [comment]
v12.22.9

**Comment by WriteThatDown** [comment]
I use linux btw (mint)

**Comment by brettz9** [comment]
The minimum version should have been set at Node 14. My personal suggestion is to use something like nvm to be able to switch and update Node versions more easily.

**Comment by WriteThatDown** [comment]
It now works, but it says that `TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined` but I don't know where to put the argument for the `manifest.json` path name. I tried just putting it after the name of the command like `npx convert-manifest-format --firefox manifest.json`, though that didn't work either.

**Comment by brettz9** [comment]
what line number of the file gave an error? The manifest.json path should just be looking for `manifest.json` in the current working directory--no need to specify a path. The other paths will be either `manifest.background.scripts[0]` or `manifest.background.service_worker`, depending on the mode (the latter is Firefox).

**Comment by WriteThatDown** [comment]
My folder structure where I'm running this command looks like this:
```
background.js  icon    libs      manifest.json  option.html  options.css
chrome.js      in.css  _locales  _metadata      option.js    style.css
```
And the full error output is
```
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at open (node:internal/fs/promises:591:10)
    at readFile (node:internal/fs/promises:1042:20)
    at file:///home/backsideofdawn/node_modules/convert-manifest-format/bin/index.js:19:26 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v20.5.1
```

**Comment by brettz9** [comment]
If you are using `--firefox`, it is expected that your `manifest.json` has a field `background: {service_worker: '...'}`.
